// <auto-generated />
using System;
using HRMS_v2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRMS_v2.Migrations
{
    [DbContext(typeof(HRMSContext))]
    [Migration("20210107045655_LimitStrings")]
    partial class LimitStrings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HRMS_v2.Models.TblAttedancePolicyMapping", b =>
                {
                    b.Property<int>("AttendancePolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("AttendancePolicyId")
                        .HasColumnType("int")
                        .HasColumnName("attendance_policy_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("AttendancePolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_atte__BF2DB5653EE532D4");

                    b.ToTable("tbl_attedance_policy_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblComboPolicyMapping", b =>
                {
                    b.Property<int>("ComboPolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("combo_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("ComboPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("combo_policy_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("ComboPolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_comb__091EB42BDA8FCBF4");

                    b.ToTable("tbl_combo_policy_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblCombooff", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("combo_Id")
                        .UseIdentityColumn();

                    b.Property<bool?>("ApprovedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("approved_status");

                    b.Property<DateTime>("ComboEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("combo_end_date");

                    b.Property<int>("ComboPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("combo_policy_Id");

                    b.Property<DateTime>("ComboStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("combo_start_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("ComboId")
                        .HasName("PK__tbl_comb__18F6468B79BA15E1");

                    b.ToTable("tbl_combooff");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id")
                        .UseIdentityColumn();

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("address3");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("PinCode")
                        .HasColumnType("int")
                        .HasColumnName("pin_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("AddressId")
                        .HasName("PK__tbl_empl__CAA247C8DDBDE6E3");

                    b.ToTable("tbl_employe_address");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<DateTime>("EmployeeDob")
                        .HasColumnType("date")
                        .HasColumnName("employee_dob");

                    b.Property<string>("EmployeeOfficalEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_offical_email");

                    b.Property<string>("BiometricMappingId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("biometric_mapping_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<string>("EmployeeContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_contact_no");

                    b.Property<int>("EmployeeCurrentAddress")
                        .HasColumnType("int")
                        .HasColumnName("employee_current_address");

                    b.Property<int>("EmployeeDesignation")
                        .HasColumnType("int")
                        .HasColumnName("employee_designation");

                    b.Property<DateTime>("EmployeeDoj")
                        .HasColumnType("date")
                        .HasColumnName("employee_doj");

                    b.Property<DateTime?>("EmployeeDor")
                        .HasColumnType("date")
                        .HasColumnName("employee_dor");

                    b.Property<string>("EmployeeEmergencyNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_emergency_no");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_first_name");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_last_name");

                    b.Property<string>("EmployeeMiddleName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_middle_name");

                    b.Property<string>("EmployeeMotherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_mother_name");

                    b.Property<int>("EmployeePermenetAddress")
                        .HasColumnType("int")
                        .HasColumnName("employee_permenet_address");

                    b.Property<string>("EmployeePersonalEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_personal_email");

                    b.Property<string>("EmpoyeeFatherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("empoyee_father_name");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeeId", "OrganizationId", "EmployeeCode", "Gender", "EmployeeDob", "EmployeeOfficalEmail")
                        .HasName("PK__tbl_empl__2C6B611403CFCA71");

                    b.ToTable("tbl_employee");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeAttendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("AttendanceYear")
                        .HasColumnType("int");

                    b.Property<int>("AttendanceMonth")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Day1")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day10")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day11")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day12")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day13")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day14")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day15")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day16")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day17")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day18")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day19")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day2")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day20")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day21")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day22")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day23")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day24")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day25")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day26")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day27")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day28")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day29")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day3")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day30")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day31")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day4")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day5")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day6")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day7")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day8")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Day9")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("AttendanceId", "OrganizationId", "EmployeeId", "AttendanceYear", "AttendanceMonth")
                        .HasName("PK__tbl_empl__B296D93B55B45DE3");

                    b.ToTable("tbl_employee_attendance");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeBankDetail", b =>
                {
                    b.Property<int>("EmployeeBankDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_bank_details_Id")
                        .UseIdentityColumn();

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("account_number");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("bank_name");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("branch_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ifsc_code");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeeBankDetailsId")
                        .HasName("PK__tbl_empl__F2C68E6C5ADC3539");

                    b.ToTable("tbl_employee_bank_details");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeBiomatricLog", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_entry_Id")
                        .UseIdentityColumn();

                    b.Property<string>("BiometricId")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("biometric_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime>("LogEntryDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("log_entry_date_time");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("organization_code");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LogEntryId")
                        .HasName("PK__tbl_empl__706632FF77F507BC");

                    b.ToTable("tbl_employee_biomatric_log");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeDocument", b =>
                {
                    b.Property<int>("EmployeeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_document_Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<string>("DocuemntFilePath")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("docuemnt_file_path");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("document_name");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeeDocumentId")
                        .HasName("PK__tbl_empl__A3E75CB80DCB598E");

                    b.ToTable("tbl_employee_document");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeMenuMapping", b =>
                {
                    b.Property<int>("MenuMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("BankName")
                        .HasColumnType("int")
                        .HasColumnName("bank_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("MenuMappingId")
                        .HasName("PK__tbl_empl__34627EAF0C91B210");

                    b.ToTable("tbl_employee_menu_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeePayrollDetail", b =>
                {
                    b.Property<int>("EmployeePayrollDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_payroll_details_Id")
                        .UseIdentityColumn();

                    b.Property<byte[]>("BasicAmount")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("basic_amount");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<byte[]>("DaAmount")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("da_amount");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<byte[]>("EmployeeCross")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("employee_cross");

                    b.Property<byte[]>("EmployeeCtc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("employee_ctc");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<byte[]>("HraAmount")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("hra_amount");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("PaySlipFilePath")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("pay_slip_file_path");

                    b.Property<int>("PayrollMonth")
                        .HasColumnType("int")
                        .HasColumnName("payroll_month");

                    b.Property<int>("PayrollYear")
                        .HasColumnType("int")
                        .HasColumnName("payroll_year");

                    b.Property<byte[]>("PfEmployee")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("pf_employee");

                    b.Property<byte[]>("PfEmployeer")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("pf_employeer");

                    b.Property<byte[]>("ProfessionalTax")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("professional_tax");

                    b.Property<byte[]>("SpeicalAllowance")
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("speical_allowance");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeePayrollDetailsId")
                        .HasName("PK__tbl_empl__191E55D0110E6869");

                    b.ToTable("tbl_employee_payroll_details");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeReportingMapping", b =>
                {
                    b.Property<int>("EmployeeMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("FirstLevelReporting")
                        .HasColumnType("int")
                        .HasColumnName("first_level_reporting");

                    b.Property<int?>("SecondLevelReporting")
                        .HasColumnType("int")
                        .HasColumnName("second_level_reporting");

                    b.Property<int?>("ThirdLevelReporting")
                        .HasColumnType("int")
                        .HasColumnName("third_level_reporting");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeeMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_empl__C6D0DCB1091F3A56");

                    b.ToTable("tbl_employee_reporting_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeSalary", b =>
                {
                    b.Property<int>("EmployeeSalaryInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_salary_info_Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<byte[]>("SalaryAnualCross")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("salary_anual_cross");

                    b.Property<byte[]>("SalaryAnualCtc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("salary_anual_ctc");

                    b.Property<int>("SalaryMonth")
                        .HasColumnType("int")
                        .HasColumnName("salary_month");

                    b.Property<byte[]>("SalaryMonthCross")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("salary__month_cross");

                    b.Property<byte[]>("SalaryMonthCtc")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varbinary(1)")
                        .HasColumnName("Salary_month_ctc");

                    b.Property<int>("SalaryYear")
                        .HasColumnType("int")
                        .HasColumnName("salary_year");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("EmployeeSalaryInfoId")
                        .HasName("PK__tbl_empl__5C5B7B90771F4775");

                    b.ToTable("tbl_employee_salary");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblEmployeeWebLogin", b =>
                {
                    b.Property<int>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_entry_Id")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("LogEntryDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("log_entry_date_time");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("log_type");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LogEntryId")
                        .HasName("PK__tbl_empl__706632FF566C05C7");

                    b.ToTable("tbl_employee_web_login");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblHolidayPolicyMapping", b =>
                {
                    b.Property<int>("HolidayPolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holiday_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("HolidayPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("holiday_policy_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("HolidayPolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_holi__E3D25386B0CE9DF7");

                    b.ToTable("tbl_holiday_policy_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblLeave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_Id")
                        .UseIdentityColumn();

                    b.Property<bool?>("ApprovedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("approved_status");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<decimal>("LeaveDays")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("leave_days");

                    b.Property<DateTime>("LeaveEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("leave_end_date");

                    b.Property<int>("LeavePolicyId")
                        .HasColumnType("int")
                        .HasColumnName("leave_policy_Id");

                    b.Property<DateTime>("LeaveStartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("leave_start_date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int")
                        .HasColumnName("leave_type_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LeaveId")
                        .HasName("PK__tbl_leav__743C549440AC1E30");

                    b.ToTable("tbl_leave");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblLeavePolicyMapping", b =>
                {
                    b.Property<int>("LeavePolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("LeavePolicyId")
                        .HasColumnType("int")
                        .HasColumnName("leave_policy_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LeavePolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_leav__F0BA63ECB7604EC2");

                    b.ToTable("tbl_leave_policy_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterAttendancePolicy", b =>
                {
                    b.Property<int>("AttendancePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("AttendacePolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("attendace_policy_name");

                    b.Property<bool>("LopFlag")
                        .HasColumnType("bit")
                        .HasColumnName("lop_flag");

                    b.Property<string>("LoginType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_type");

                    b.Property<bool>("AttendaceFlag")
                        .HasColumnType("bit")
                        .HasColumnName("attendace_flag");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("LopHours")
                        .HasColumnType("int")
                        .HasColumnName("lop_hours");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("AttendancePolicyId", "OrganizationId", "AttendacePolicyName", "LopFlag", "LoginType", "AttendaceFlag")
                        .HasName("PK__tbl_mast__820552CE3C6652C0");

                    b.ToTable("tbl_master_attendance_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterComboPolicy", b =>
                {
                    b.Property<int>("ComboPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("combo_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("ComboPolicyName")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("combo_policy_name");

                    b.Property<string>("ComboMinHours")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("combo_min_hours");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("ComboPolicyId", "OrganizationId", "ComboPolicyName", "ComboMinHours")
                        .HasName("PK__tbl_mast__141AF1EA8DA91F84");

                    b.ToTable("tbl_master_combo_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterHolidayList", b =>
                {
                    b.Property<int>("HolidayPolicylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holiday_policylist_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("HolidayPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("holiday_policy_Id");

                    b.Property<string>("HolidayDate")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("holiday_date");

                    b.Property<int>("HolidayYear")
                        .HasColumnType("int")
                        .HasColumnName("holiday_year");

                    b.Property<int>("HolidayMonth")
                        .HasColumnType("int")
                        .HasColumnName("holiday_month");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<string>("Holidayname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("holidayname");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("HolidayPolicylistId", "OrganizationId", "HolidayPolicyId", "HolidayDate", "HolidayYear", "HolidayMonth")
                        .HasName("PK__tbl_mast__87570F718E0B3FDA");

                    b.ToTable("tbl_master_holiday_list");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterHolidayPolicy", b =>
                {
                    b.Property<int>("HolidayPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("holiday_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("HolidayPolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("holiday_policy_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("HolidayPolicyId", "OrganizationId", "HolidayPolicyName")
                        .HasName("PK__tbl_mast__2198DBB52A9AD866");

                    b.ToTable("tbl_master_holiday_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterLeavePolicy", b =>
                {
                    b.Property<int>("LeavePolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_policy_id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("LeavePolicyType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("leave_policy_type");

                    b.Property<string>("LeaveType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("leave_type");

                    b.Property<string>("LeaveTypeShortName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("leave_type_short_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("TotalLeaveDays")
                        .HasColumnType("int")
                        .HasColumnName("total_leave_days");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LeavePolicyId", "OrganizationId", "LeavePolicyType", "LeaveType", "LeaveTypeShortName")
                        .HasName("PK__tbl_mast__459170E5590C09B5");

                    b.ToTable("tbl_master_leave_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterLeaveSubPolicy", b =>
                {
                    b.Property<int>("LeaveSubPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_sub_policy_id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<int>("LeavePolicyId")
                        .HasColumnType("int")
                        .HasColumnName("leave_policy_id");

                    b.Property<string>("LeaveType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("leave_type");

                    b.Property<string>("LeaveTypeShortName")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("leave_type_short_name");

                    b.Property<double?>("CarryForwardDays")
                        .HasColumnType("float")
                        .HasColumnName("carry_forward_days");

                    b.Property<bool?>("CarryForwardFlag")
                        .HasColumnType("bit")
                        .HasColumnName("carry_forward_flag");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<double>("LeaveDays")
                        .HasColumnType("float")
                        .HasColumnName("leave_days");

                    b.Property<bool>("PaidLeaveFlag")
                        .HasColumnType("bit")
                        .HasColumnName("paid_leave_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("LeaveSubPolicyId", "OrganizationId", "LeavePolicyId", "LeaveType", "LeaveTypeShortName")
                        .HasName("PK__tbl_mast__CBFCAA9A9743027B");

                    b.ToTable("tbl_master_leave_sub_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterMenuList", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("MenuName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("menu_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("MenuId", "OrganizationId", "MenuName")
                        .HasName("PK__tbl_mast__8DEFE427BE56ECB6");

                    b.ToTable("tbl_master_menu_list");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterPayrollSetting", b =>
                {
                    b.Property<int>("PayrollPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payroll_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("PayrollPolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payroll_policy_name");

                    b.Property<decimal>("BasicPercentage")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("basic_percentage");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<decimal>("DaPercentage")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("da_percentage");

                    b.Property<decimal>("HraPercentage")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("hra_percentage");

                    b.Property<decimal?>("PfEmployeeAmount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("pf_employee_amount");

                    b.Property<decimal?>("ProfessionalTax")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("professional_tax");

                    b.Property<decimal?>("SpecialAllowance")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("special_allowance");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("PayrollPolicyId", "OrganizationId", "PayrollPolicyName", "BasicPercentage", "DelFlag", "CreatedDate")
                        .HasName("PK__tbl_mast__04A67A302B325933");

                    b.ToTable("tbl_master_payroll_setting");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterPermissionPolicy", b =>
                {
                    b.Property<int>("PermissionPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permission_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("PermissionPolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("permission_policy_name");

                    b.Property<string>("PemissionPolicyType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pemission_policy_type");

                    b.Property<int>("PemissionCount")
                        .HasColumnType("int")
                        .HasColumnName("pemission_count");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("PemissionMins")
                        .HasColumnType("int")
                        .HasColumnName("pemission_mins");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("PermissionPolicyId", "OrganizationId", "PermissionPolicyName", "PemissionPolicyType", "PemissionCount")
                        .HasName("PK__tbl_mast__656A89E58838D426");

                    b.ToTable("tbl_master_permission_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterShiftPolicy", b =>
                {
                    b.Property<int>("ShiftPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shift_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<string>("ShiftPolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("shift_policy_name");

                    b.Property<string>("ShiftStartTime")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("shift_start_time");

                    b.Property<string>("ShiftEndTime")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("shift_end_time");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("ShiftHours")
                        .HasColumnType("int")
                        .HasColumnName("shift_hours");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("ShiftPolicyId", "OrganizationId", "ShiftPolicyName", "ShiftStartTime", "ShiftEndTime")
                        .HasName("PK__tbl_mast__01138C4BEEDD7705");

                    b.ToTable("tbl_master_shift_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblMasterWeekoffPolicy", b =>
                {
                    b.Property<int>("WeekoffPolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("weekoff_policy_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("WeekoffPolicyName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("weekoff_policy_name");

                    b.Property<string>("WeekoffDays")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("weekoff_days");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("WeekoffPolicyId", "OrganizationId", "WeekoffPolicyName", "WeekoffDays")
                        .HasName("PK__tbl_mast__9B7B7198C3966B62");

                    b.ToTable("tbl_master_weekoff_policy");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblOrganization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("organization_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationName")
                        .HasColumnType("int")
                        .HasColumnName("organization_name");

                    b.Property<string>("OrganizationEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("organization_email");

                    b.Property<string>("OrganizationContact")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("organization_contact");

                    b.Property<string>("OrganizationCode")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("organization_code");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<string>("OrganizationAddress1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("organization_address1");

                    b.Property<string>("OrganizationAddress2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("organization_address2");

                    b.Property<string>("OrganizationLogo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("organization_logo");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("organization_type");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pin_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("OrganizationId", "OrganizationName", "OrganizationEmail", "OrganizationContact", "OrganizationCode")
                        .HasName("PK__tbl_orga__EBE7D72C9F4C6DD6");

                    b.ToTable("tbl_organization");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblOrganizationRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_id");

                    b.Property<string>("RoleName")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("role_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("RoleId", "OrganizationId", "RoleName")
                        .HasName("PK__tbl_orga__FB7A78DB82A7EC4E");

                    b.ToTable("tbl_organization_role");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblPermission", b =>
                {
                    b.Property<int>("PemissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pemission_Id")
                        .UseIdentityColumn();

                    b.Property<bool?>("ApprovedStatus")
                        .HasColumnType("bit")
                        .HasColumnName("approved_status");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("PemissionPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("pemission_policy_Id");

                    b.Property<DateTime>("PermissionStartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("permission_start_time");

                    b.Property<DateTime>("PesmissionEndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("pesmission_end_time");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("PemissionId")
                        .HasName("PK__tbl_perm__101DF0C7311746E7");

                    b.ToTable("tbl_permission");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblShiftPolicyMapping", b =>
                {
                    b.Property<int>("ShiftPolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shift_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<int>("ShiftPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("shift_policy_Id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.HasKey("ShiftPolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_shif__2438ADB84CDDD8C7");

                    b.ToTable("tbl_shift_policy_mapping");
                });

            modelBuilder.Entity("HRMS_v2.Models.TblWeekoffPolicyMapping", b =>
                {
                    b.Property<int>("WeekoffPolicyMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("weekoff_policy_mapping_Id")
                        .UseIdentityColumn();

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int")
                        .HasColumnName("organization_Id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_Id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DelFlag")
                        .HasColumnType("bit")
                        .HasColumnName("del_flag");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_date");

                    b.Property<int>("WeekoffPolicyId")
                        .HasColumnType("int")
                        .HasColumnName("weekoff_policy_Id");

                    b.HasKey("WeekoffPolicyMappingId", "OrganizationId", "EmployeeId")
                        .HasName("PK__tbl_week__A44F72CBD121D624");

                    b.ToTable("tbl_weekoff_policy_mapping");
                });
#pragma warning restore 612, 618
        }
    }
}
